FROM rust:slim-buster
RUN apt-get -y update
RUN apt-get install -y sudo

WORKDIR /app
EXPOSE 80
ENV PYTHONUNBUFFERED 1

RUN set -x && \
	apt-get update && \
	apt -f install	&& \
	apt-get install -y python3 make build-essential libssl-dev zlib1g-dev libbz2-dev default-libmysqlclient-dev && \
	apt-get install -y libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev && \
	apt-get install -y xz-utils tk-dev libffi-dev liblzma-dev python-openssl git && \
	apt-get install -y python3-pip && \
	apt-get -qy install netcat && \
	rm -rf /var/lib/apt/lists/* && \
	wget -O /wait-for https://raw.githubusercontent.com/eficode/wait-for/master/wait-for && \
	chmod +x /wait-for && \
	curl https://pyenv.run | bash


ENV HOME /root
ENV PYENV_ROOT $HOME/.pyenv
ENV CARGO_ROOT /usr/local/cargo
ENV PATH $CARGO_ROOT/bin:$PATH
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
 
RUN pyenv install 3.7.2
RUN pyenv global 3.7.2

RUN pip install --upgrade pip

CMD ["sh", "/entrypoint-web.sh"]
COPY . .

COPY requirements.txt ./
RUN pip install -r requirements.txt --no-cache-dir

RUN python -c "import nltk;nltk.download('punkt')"
RUN python -m spacy download en_core_web_lg  --no-cache-dir
COPY . ./