version: "3"

services:
  summarizer:
    build: 
      context: .
      args:
        REQUIREMENTS_FILE: dev.txt
    image: sounder_summarizer
    container_name: api_summarizer
    environment:
      - FLASK_DEBUG=1  # TODO change
    ports:
      - "5006:5006"
    volumes:
      - .:/summarizer
    depends_on:
      - database

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database-data:/var/lib/mysql

volumes:
  database-data:
