version: "3"

networks:
  conga_micro_network:
    external:
      name: conga_micro_network

services:
  custom_extraction:
    build: 
      context: .
      args:
        REQUIREMENTS_FILE: dev.txt
    image: conga_custom_extraction
    # container_name: api_custom_extraction
    environment:
      - FLASK_DEBUG=1
    ports:
      - "5006:5006"
    networks:
      - conga_micro_network
    volumes:
      - .:/custom-extraction
    depends_on:
      - database

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database-data:/var/lib/mysql
    networks:
      - conga_micro_network

  celery:
    image: conga_custom_extraction
    restart: unless-stopped
    env_file: .env
    command: 'sh -c "celery -A app worker --pool solo --loglevel=debug --concurrency=4"'
    volumes:
      - .:/custom-extraction
    networks:
      - conga_micro_network

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: --port 6380
    ports:
      - 6380:6380
    networks:
      - conga_micro_network

volumes:
  database-data:
