FROM python:3.8

ARG REQUIREMENTS_FILE

WORKDIR /field-extraction

COPY ./requirements/ ./requirements
RUN pip install -r ./requirements/${REQUIREMENTS_FILE}
RUN python -c "import nltk;nltk.download('punkt')"
RUN python -m spacy download en_core_web_lg

COPY . .

EXPOSE 5004

CMD [ "python", "./run_consumers.py" ]